

server:
  port: 8080
#  servlet:
#    context-path: /shopping
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/outpatient?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf8&autoReconnect=true&allowMultiQueries=true
    username: root
    password: 123456
  mvc:
    static-path-pattern: /**
  resources:
    static-locations: classpath:/META-INF/resources/,classpath:/resources/,classpath:/static/,classpath:/public/
  redis:
      host: 192.168.163.131
      port: 6379
      password:
      database: 0
#logging:
#  level:
#    com.system.mapper: debug
logging.level.org.springframework.boot.autoconfigure: error
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl